### ISSUE TITLE
Persistent volume required for the nozzle?

### ISSUE THREAD

**Issue by j-kaplan** [cloudfoundry-incubator/noisy-neighbor-nozzle-release#4]
The example manifest shows a persistent volume for the nozzles: https://github.com/cloudfoundry-incubator/noisy-neighbor-nozzle-release/blob/master/manifests/noisy-neighbor-nozzle.yml#L18

Is this necessary?

**Comment by bradylove** [comment]
It is not necessary, I have created PR #5 to remove it.
