### ISSUE TITLE
Trouble querying the accumulator manually

### ISSUE THREAD

**Issue by j-kaplan** [cloudfoundry-incubator/noisy-neighbor-nozzle-release#6]
From the code it looks like the accumulator can be queried with a request to /rates/{timestamp} however I seem to only get 404s:

```
$ http http://10.81.43.210:8080/rates/1513971645  Authorization:"$(cat ~/.cf/config.json | jq -r .AccessToken)"
HTTP/1.1 404 Not Found
Content-Length: 0
Content-Type: text/plain; charset=utf-8
Date: Fri, 22 Dec 2017 19:49:20 GMT
```

I can see that when I call the accumulator it is making the requests to the nozzles:
```
2017/12/22 19:23:53 Server bound to 0.0.0.0:8080
10.81.43.210 - - [22/Dec/2017:19:41:30 +0000] "GET /rates/1513971199 HTTP/1.1" 404 0
10.81.43.210 - - [22/Dec/2017:19:44:55 +0000] "GET /rates/1513971645 HTTP/1.1" 404 0
10.81.43.210 - - [22/Dec/2017:19:45:45 +0000] "GET /rates/1513971645 HTTP/1.1" 404 0
10.81.43.210 - - [22/Dec/2017:19:47:26 +0000] "GET /rates/1513971645 HTTP/1.1" 404 0
10.81.43.210 - - [22/Dec/2017:19:49:19 +0000] "GET /rates/1513971645 HTTP/1.1" 404 0
10.81.43.210 - - [22/Dec/2017:19:55:16 +0000] "GET /rates/1513971645 HTTP/1.1" 404 0
```

**Comment by bradylove** [comment]
Hey @j-kaplan,

Sorry we are lacking documentation on this so far. 

The nozzle will collect log and store rates by the minute by default. Every minute it takes the log rates and stores them in an in memory store. Rates are retained for 1 hour by default. To query the rates the timestamp your timestamp should be truncated to the minute. For example, your timestamp, `1513971645` is `Friday, December 22, 2017 7:40:45 PM`, instead you should query for `1513971600` which is ` Friday, December 22, 2017 7:40:00 PM`.

Also keep in mind that when you have multiple nozzles deployed, they can have different timestamps, so we recommend querying for rates ~1.5 minutes ago (truncated of course to the nearest minute of course)

If the accumulator was to automatically truncate your timestamp for you would you find this helpful or more confusing?

**Comment by j-kaplan** [comment]
Hey @bradylove thanks for the info. I see the docs have been updated now as well. I was able to get it working by truncating to the nearest minute.

As far as automatically truncating, I don't know if that would cause any unintended side-effects for any reporters, but at the very least an optional query parameter to truncate would certainly be useful if an operator were to need to manually query the accumulator for any reason.

**Comment by bradylove** [comment]
@j-kaplan I am glad you were able to figure it out. I went ahead and created a [PR](https://github.com/cloudfoundry/noisy-neighbor-nozzle/pull/10) to add a `truncate_timestamp` query parameter to truncate the timestamp on server side. The timestamp in the response body will return the actual timestamp that can be used when indexing the results.

I am going to close this issue for now, if you come across anything else please let us know.
