### ISSUE TITLE
The Log Noise plugin isn't compatible with the bosh release

### ISSUE THREAD

**Issue by MasslessParticle** [cloudfoundry-incubator/noisy-neighbor-nozzle-release#9]
This should be noted in the release documentation and the nozzle documentation.

**Comment by bradylove** [comment]
@MasslessParticle this could also be resolved by adding the [route-registrar from the routing release](https://github.com/cloudfoundry/routing-release/tree/develop/jobs/route_registrar) to register the `nn-accumulator` route.

**Comment by jtuchscherer** [comment]
We are planning to deprecate the noisy neighbor bosh release - https://www.pivotaltracker.com/story/show/160111476
